'use strict';
const $ = (s) => document.querySelector(s);
const activities = [
  {name:'Click', title:'Pick a little joy.', instruction:'Move to a flower. Press the left button once, then let go. Pick all 5!', tip:'Rest your hand on the mouse. Move it gently on the table.', guide:'left', caption:'Press and let go', feedback:'Point at a flower. Give it a click!'},
  {name:'Drag', title:'Find their homes.', instruction:'Hold the left button on a shape. Move it to its matching home. Let go!', tip:'Keep the button held down while you move. Missed it? Try again!', guide:'left', caption:'Hold → move → let go', feedback:'Match each shape to the same symbol.'},
  {name:'Scroll', title:'A little discovery.', instruction:'Put your pointer in the trail. Roll the wheel down to find a star.', tip:'Keep your mouse still. Only your finger needs to roll the wheel.', guide:'wheel', caption:'Roll the little wheel', feedback:'Follow the trail down. What will you find?'},
  {name:'Zoom', title:'Near, then far.', instruction:'Point at the cube. Roll the wheel up to get closer. Then roll down to move away.', tip:'Zoom changes how big things look. The shape itself stays the same.', guide:'wheel', caption:'Roll up ↔ roll down', feedback:'First, zoom in until the cube looks bigger.'},
  {name:'Look around', title:'See another side.', instruction:'Hold the right button in the maker space. Move sideways. Let go to stop.', tip:'This is called orbiting. You are moving your view around the shape!', guide:'right', caption:'Hold right → move', feedback:'Look around until you find the star on the back.'}
];
let current=0, completed=new Set(), cleanup=()=>{};
const stage=$('#stage');
function say(text){$('#feedback').textContent=text;}
function complete(message){completed.add(current);$('#next').disabled=false;say(message);renderSteps();}
function renderSteps(){ $('#steps').innerHTML=activities.map((a,i)=>`<button class="step ${completed.has(i)?'done':''}" ${i===current?'aria-current="step"':''} data-step="${i}"><span class="step-number">${completed.has(i)?'✓':i+1}</span>${a.name}</button>`).join(''); }
$('#steps').addEventListener('click',e=>{const b=e.target.closest('[data-step]');if(b)render(Number(b.dataset.step),true);});
function render(index,focus=false){
  cleanup();cleanup=()=>{};if('speechSynthesis' in window)speechSynthesis.cancel();current=index;const a=activities[index];
  renderSteps();$('#step-label').textContent=`ACTIVITY ${index+1} OF 5`;$('#activity-title').textContent=a.title;$('#instruction').textContent=a.instruction;$('#tip').textContent=a.tip;$('.mouse-guide').className=`mouse-guide guide-${a.guide}`;$('#mouse-caption').textContent=a.caption;$('#counter').textContent='';$('#next').disabled=!completed.has(current);$('#next').innerHTML=index===4?'Finish <span aria-hidden="true">→</span>':'Next activity <span aria-hidden="true">→</span>';say(a.feedback);stage.innerHTML='';
  [clickActivity,dragActivity,scrollActivity,zoomActivity,orbitActivity][index]();if(focus)$('#activity-title').focus();
}
function clickActivity(){let count=0;const positions=[[15,16],[60,12],[38,40],[12,65],[72,62]];positions.forEach(([x,y],i)=>{const b=document.createElement('button');b.className='flower';b.style.left=x+'%';b.style.top=y+'%';b.textContent='✿';b.setAttribute('aria-label',`Pick flower ${i+1}`);b.onclick=()=>{b.disabled=true;b.classList.add('collected');b.textContent='✓';$('#counter').textContent=`${++count} / 5 flowers`;if(count===5)complete('Lovely picking! You know how to click.');else say('You got it! Find another flower.');};stage.append(b);});$('#counter').textContent='0 / 5 flowers';}
function dragActivity(){
  let count=0, selected=null, drag=null;const symbols={square:'■',circle:'●',triangle:'▲'};
  function match(shape,home){shape.hidden=true;home.classList.add('matched');home.disabled=true;home.textContent='✓';home.setAttribute('aria-label',`${shape.dataset.shape} matched`);selected=null;$('#counter').textContent=`${++count} / 3 shapes`;if(count===3)complete('All at home! Great moving, maker.');else say('A perfect match! Try the next shape.');}
  for(const [i,type] of Object.keys(symbols).entries()){const shape=document.createElement('button'),home=document.createElement('button');shape.className='shape';home.className='home';shape.dataset.shape=home.dataset.shape=type;shape.textContent=home.textContent=symbols[type];shape.style.left='12%';shape.style.top=home.style.top=(12+i*31)+'%';shape.setAttribute('aria-label',`Move ${type}`);home.setAttribute('aria-label',`${type} home`);shape.onclick=()=>{if(shape.hidden)return;stage.querySelectorAll('.selected').forEach(b=>b.classList.remove('selected'));selected=shape;shape.classList.add('selected');say(`Now click the ${type} home, or drag the shape there.`);};home.onclick=()=>{if(selected?.dataset.shape===type)match(selected,home);else say('Choose the shape with the same symbol first.');};
    shape.onpointerdown=e=>{if(e.button!==0)return;const r=shape.getBoundingClientRect();drag={shape,home,x:e.clientX,y:e.clientY,left:shape.style.left,top:shape.style.top,dx:e.clientX-r.left,dy:e.clientY-r.top,moved:false};shape.setPointerCapture(e.pointerId);};
    shape.onpointermove=e=>{if(!drag||drag.shape!==shape)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<5&&!drag.moved)return;drag.moved=true;shape.classList.add('dragging');const r=stage.getBoundingClientRect();shape.style.left=Math.max(0,Math.min(r.width-82,e.clientX-r.left-drag.dx))+'px';shape.style.top=Math.max(0,Math.min(r.height-82,e.clientY-r.top-drag.dy))+'px';};
    function end(e,cancel=false){if(!drag||drag.shape!==shape)return;const d=drag;drag=null;shape.classList.remove('dragging');if(shape.hasPointerCapture(e.pointerId))shape.releasePointerCapture(e.pointerId);if(!d.moved&&!cancel)return;const r=home.getBoundingClientRect(),s=shape.getBoundingClientRect();if(!cancel&&s.left+s.width/2>=r.left-14&&s.left+s.width/2<=r.right+14&&s.top+s.height/2>=r.top-14&&s.top+s.height/2<=r.bottom+14)match(shape,home);else{shape.style.left=d.left;shape.style.top=d.top;say('Almost! Hold the button until you reach the matching home.');}}
    shape.onpointerup=e=>end(e);shape.onpointercancel=e=>end(e,true);stage.append(home,shape);
  }$('#counter').textContent='0 / 3 shapes';
}
function scrollActivity(){stage.innerHTML='<div class="scroll-window" tabindex="0" role="region" aria-label="Discovery trail. Scroll down to the star, then back up."><div class="scroll-content"><button id="trail-top">Back at the start!</button><p>Roll the wheel down<br>↓</p><span aria-hidden="true">🌱</span><p>Keep exploring…</p><span aria-hidden="true">🌼</span><p>Almost there…</p><button id="trail-star" aria-label="Collect the star">★ Found it!</button></div></div>';let found=false;$('#trail-star').onclick=()=>{found=true;$('#trail-star').textContent='✓ Star collected';say('You found it! Roll the wheel up to the start.');$('#counter').textContent='1 / 2 discoveries';};$('#trail-top').onclick=()=>{if(found)complete('Down and back up. That’s scrolling!');else say('Roll down the trail to find the star first.');};const trail=$('.scroll-window');trail.onscroll=()=>{if(found&&trail.scrollTop<15){$('#counter').textContent='2 / 2 discoveries';complete('Down and back up. That’s scrolling!');}};$('#counter').textContent='0 / 2 discoveries';}
function cubeMarkup(){return '<div class="cube"><div class="face front">●</div><div class="face back">★</div><div class="face right">＋</div><div class="face left">◆</div><div class="face top">✿</div><div class="face bottom"></div></div>';}
function setupView(label){stage.innerHTML=`<div class="view-scene" tabindex="0" role="region" aria-label="${label}">${cubeMarkup()}</div>`;return $('.view-scene');}
function zoomActivity(){const view=setupView('Zoom practice. Use the mouse wheel or plus and minus keys.');stage.insertAdjacentHTML('beforeend','<span class="zoom-label">100%</span><div class="view-controls"><button id="zoom-out" aria-label="Zoom out">−</button><button id="zoom-in" aria-label="Zoom in">+</button></div><p class="stage-hint">Roll up to get closer · roll down to move away</p>');let scale=1,near=false;
function zoom(delta){scale=Math.max(.55,Math.min(1.8,scale+delta));$('.cube').style.transform=`scale(${scale}) rotateX(-22deg) rotateY(-32deg)`;$('.zoom-label').textContent=Math.round(scale*100)+'%';if(!near&&scale>=1.45){near=true;say('Nice and close! Now roll down to make it smaller.');$('#counter').textContent='1 / 2 views';}if(near&&scale<=.85){$('#counter').textContent='2 / 2 views';complete('Near and far! You can zoom your view.');}}
view.addEventListener('wheel',e=>{if(e.ctrlKey||e.metaKey)return;e.preventDefault();if(e.deltaY)zoom(-Math.sign(e.deltaY)*.09);},{passive:false});view.onkeydown=e=>{if(['+','=','-','_'].includes(e.key)){e.preventDefault();zoom(e.key==='-'||e.key==='_'?-.12:.12);}};$('#zoom-in').onclick=()=>zoom(.12);$('#zoom-out').onclick=()=>zoom(-.12);$('#counter').textContent='0 / 2 views';}
function orbitActivity(){const view=setupView('Orbit practice. Hold the right mouse button and drag sideways, or use the left and right arrow keys.');stage.insertAdjacentHTML('beforeend','<p class="stage-hint">Hold the right button + move sideways</p>');let angle=-32,drag=null;const update=()=>{$('.cube').style.transform=`rotateX(-22deg) rotateY(${angle}deg)`;const normal=((angle%360)+360)%360;$('#counter').textContent='Find the ★';if(normal>145&&normal<215){$('#counter').textContent='★ Found!';complete('You found the star! You can look around a 3D shape.');}};view.oncontextmenu=e=>e.preventDefault();view.onpointerdown=e=>{if(e.button!==2)return;e.preventDefault();drag={x:e.clientX,angle};view.setPointerCapture(e.pointerId);};view.onpointermove=e=>{if(drag){angle=drag.angle+(e.clientX-drag.x)*.8;update();}};view.onpointerup=view.onpointercancel=e=>{drag=null;if(view.hasPointerCapture(e.pointerId))view.releasePointerCapture(e.pointerId);};view.onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();angle+=e.key==='ArrowRight'?15:-15;update();}};$('#counter').textContent='Find the ★';}
$('#next').onclick=()=>{if(current<4){render(current+1,true);return;}if(completed.size<5){render(activities.findIndex((_,i)=>!completed.has(i)),true);return;}cleanup();stage.innerHTML='<div class="finish"><div class="finish-mark" aria-hidden="true">✳</div><h3>You’re a mouse maker!</h3><p>You clicked, dragged, scrolled, zoomed, and looked around.<br>Your next big idea is waiting.</p><button class="primary" id="play-again">Practice again ↻</button></div>';$('#activity-title').textContent='Ready to create.';$('#instruction').textContent='Give yourself a little cheer! Ask your teacher what you will make next in Tinkercad.';$('#step-label').textContent='ALL 5 ACTIVITIES COMPLETE';$('#counter').textContent='5 / 5 complete';$('#next').disabled=true;say('Great practice. You can revisit any activity above.');$('#play-again').onclick=()=>{completed.clear();render(0,true);};$('#activity-title').focus();};
$('#retry').onclick=()=>{completed.delete(current);render(current,true);};
$('#listen').onclick=()=>{if(!('speechSynthesis' in window)){say('Read-aloud isn’t available in this browser. Ask a helper to read with you.');return;}speechSynthesis.cancel();const message=new SpeechSynthesisUtterance(`${$('#activity-title').textContent} ${$('#instruction').textContent}`);message.rate=.85;message.lang='en-US';message.onerror=()=>say('The voice could not play. Ask a helper to read with you.');speechSynthesis.speak(message);};
$('#teacher').onclick=()=>$('#teacher-dialog').showModal();$('#close-teacher').onclick=()=>$('#teacher-dialog').close();
render(0);
